{"topicSections":[{"identifiers":["doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/backendHTTPError(_:)","doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/internalError(_:)","doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/invalidAPIKey","doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/noConnection"],"title":"Enumeration Cases"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/Equatable-Implementations","doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/Error-Implementations"]}],"metadata":{"role":"symbol","title":"SighticError","modules":[{"name":"SighticAnalytics"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SighticError","kind":"identifier"}],"externalID":"s:16SighticAnalytics0A5ErrorO","navigatorTitle":[{"text":"SighticError","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.sighticanalytics.SighticAnalytics\/SQ","doc:\/\/com.sighticanalytics.SighticAnalytics\/s5ErrorP","doc:\/\/com.sighticanalytics.SighticAnalytics\/SH","doc:\/\/com.sighticanalytics.SighticAnalytics\/s8SendableP"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SighticError","kind":"identifier"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Error that occurs during the analysis of a test recording by the Sightic Analytics backend."}],"seeAlsoSections":[{"title":"Errors","generated":true,"identifiers":["doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticRecordingError","doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticUserError"]}],"variants":[{"paths":["\/documentation\/sighticanalytics\/sighticerror"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics"]]},"references":{"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics":{"type":"topic","title":"SighticAnalytics","url":"\/documentation\/sighticanalytics","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics","role":"collection","abstract":[{"type":"text","text":"Predict whether a person is impaired due to alcohol consumption."}],"kind":"symbol"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/internalError(_:)":{"title":"SighticError.internalError(_:)","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/internalError(_:)","abstract":[{"text":"Internal error with an associated error code that can be provided to Sightic Analytics for troubleshooting.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/sighticanalytics\/sighticerror\/internalerror(_:)","role":"symbol"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/Equatable-Implementations","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/sighticanalytics\/sighticerror\/equatable-implementations","role":"collectionGroup"},"doc://com.sighticanalytics.SighticAnalytics/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/s8SendableP","title":"Swift.Sendable"},"doc://com.sighticanalytics.SighticAnalytics/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/s5ErrorP","title":"Swift.Error"},"doc://com.sighticanalytics.SighticAnalytics/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/SQ","title":"Swift.Equatable"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/noConnection":{"title":"SighticError.noConnection","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/noConnection","abstract":[{"type":"text","text":"Connection with Sightic backend could not be established."}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noConnection","kind":"identifier"}],"url":"\/documentation\/sighticanalytics\/sighticerror\/noconnection","role":"symbol"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError":{"type":"topic","title":"SighticError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SighticError","kind":"identifier"}],"url":"\/documentation\/sighticanalytics\/sighticerror","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SighticError"}],"abstract":[{"type":"text","text":"Error that occurs during the analysis of a test recording by the Sightic Analytics backend."}],"identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError"},"doc://com.sighticanalytics.SighticAnalytics/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/SH"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/invalidAPIKey":{"title":"SighticError.invalidAPIKey","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/invalidAPIKey","abstract":[{"type":"text","text":"Customer unique API key is invalid."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidAPIKey","kind":"identifier"}],"url":"\/documentation\/sighticanalytics\/sighticerror\/invalidapikey","role":"symbol"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/Error-Implementations":{"type":"topic","abstract":[],"kind":"article","title":"Error Implementations","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/Error-Implementations","role":"collectionGroup","url":"\/documentation\/sighticanalytics\/sighticerror\/error-implementations"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticError/backendHTTPError(_:)":{"type":"topic","title":"SighticError.backendHTTPError(_:)","abstract":[{"type":"text","text":"Sightic backend returned an HTTP error."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticError\/backendHTTPError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"backendHTTPError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/sighticanalytics\/sighticerror\/backendhttperror(_:)"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticUserError":{"abstract":[{"type":"text","text":"Error caused by the user during the alignment or test phases."}],"identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticUserError","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SighticUserError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SighticUserError"}],"kind":"symbol","title":"SighticUserError","url":"\/documentation\/sighticanalytics\/sighticusererror"},"doc://com.sighticanalytics.SighticAnalytics/documentation/SighticAnalytics/SighticRecordingError":{"title":"SighticRecordingError","identifier":"doc:\/\/com.sighticanalytics.SighticAnalytics\/documentation\/SighticAnalytics\/SighticRecordingError","abstract":[{"type":"text","text":"Error that occurs while the app user performs the test."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SighticRecordingError"}],"navigatorTitle":[{"text":"SighticRecordingError","kind":"identifier"}],"url":"\/documentation\/sighticanalytics\/sighticrecordingerror","role":"symbol"}}}